name: Generate KodeKloud Report

on:
  workflow_dispatch: # puedes correrlo manualmente desde la pestaña "Actions"

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run report generation script
        run: |
          python backend/generate_report.py blob:KodeKloud2025Admin.xlsx blob:activity_leaderboard.xlsx

      - name: Commit and push updated JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/data/kodekloud_data.json
          git commit -m "🔁 Update JSON report from Azure Blob" || echo "No changes to commit"
          git push
