name: Generate KodeKloud Report

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run report generator
        working-directory: backend
        run: |
          python generate_report.py blob:KodeKloud2025Admin.xlsx blob:activity_leaderboard.xlsx

      - name: Commit generated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/kodekloud_data.json
          git commit -m "🔁 Auto-update: kodekloud_data.json from GitHub Actions" || echo "No changes to commit"
          git push
